# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-16 14:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentrating',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='contentrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='designrating',
            name='project',
        ),
        migrations.RemoveField(
            model_name='usabilityrating',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='usabilityrating',
            name='project',
        ),
        migrations.DeleteModel(
            name='ContentRating',
        ),
        migrations.DeleteModel(
            name='DesignRating',
        ),
        migrations.DeleteModel(
            name='UsabilityRating',
        ),
    ]
